CREATE TABLE IF NOT EXISTS `USERS` (
  `ID` BIGINT(20) NOT NULL,
  `SURNAME` VARCHAR(30) NOT NULL,
  `FIRSTNAME` VARCHAR(30) NOT NULL,
  `GENDER` VARCHAR(6) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `SUBSCRIBED_NEWS_LETTER` BOOLEAN NOT NULL)