version: "3"
services:
  user-service:
    image: user-service
    ports:
      - "9001:9001"
    depends_on:
      - user-service-database
    environment:
      WAIT_HOSTS: user-service-database:3306
  user-service-database:
    image: mysql:8.0.15
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: user-service
  template-service:
    image: template-service
    ports:
      - "9002:9001"
    depends_on:
      - template-service-database
    environment:
      WAIT_HOSTS: template-service-database:3306
  template-service-database:
    image: mysql:8.0.15
    ports:
      - "3308:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: template-service
  notification-service:
    image: notification-service
    ports:
      - "9003:9001"
    environment:
      WAIT_HOSTS: user-service:9001, template-service:9001